#!/usr/bin/env sh
set -eu

case "$1" in
    getlocked)
        lock
        ;;
    suspend)
        lock
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    logout)
        i3-msg exit
        ;;
    hibernate)
        lock
        systemctl hibernate
        ;;
    *)
        echo "Usage: $0 {lock|suspend|hibernate|reboot|shutdown|logout}"
        exit 1
        ;;
esac
