#!/usr/bin/env bash
#
# Use BLOCK_INSTANCE if set, otherwise default to wlp3s0
device="${BLOCK_INSTANCE:-wlp3s0}"
if [[ $(cat /sys/class/net/$device/operstate) == "up" ]]; then  # doesn’t guarantee it’s wireless
    if [[ -d "/sys/class/net/${device}/wireless" ]]; then  
        # this tells you the interface is actually a Wi-Fi interface
        quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
        echo "<span rise='2pt' size='x-large'>󰤥 </span><span rise='3pt'>${quality}%</span>"
        if [[ "${quality}" -le 20 ]]; then
            exit 33
        fi
    else
        # Ethernet
        echo "<span rise='2pt' size='large'>󰤥</span> <span rise='3pt' >UP</span>"
    fi
else
    echo "<span rise='2pt' size='large'>󰤥</span> <span rise='3pt'>DOWN</span>"
    exit 33
fi

